import type { Metadata } from "next";
import {Poppins} from 'next/font/google'
import "./globals.scss";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Country List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
